org: kartago
service: usuarios-api-stepfunctions

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 10
  memorySize: 1024
  iam:
    role: arn:aws:iam::501635705879:role/LabRole
  environment:
    USUARIOS_TABLE: usuarios-${self:provider.stage}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  crearUsuario:
    handler: handler.crearUsuario
    events:
      - http:
          path: /usuarios/registro
          method: post
          cors: true

  loginUsuario:
    handler: handler.loginUsuario
    events:
      - http:
          path: /usuarios/login
          method: post
          cors: true

  validarToken:
    handler: handler.validarToken
    events:
      - http:
          path: /usuarios/validar
          method: get
          cors: true

resources:
  Resources:
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usuarios-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL

plugins:
  - serverless-offline
